namespace: oshvl
name: infra
version: 1.0.0
readme: README.md
authors:
  - orangeshovel
description: Shared Ansible roles for orangeshovel
license:
  - MIT
tags:
  - infrastructure
  - deployment
repository: https://github.com/orangeshovel/oshvl-ansible-shared
issues: https://github.com/orangeshovel/oshvl-ansible-shared/issues
